### ISSUE TITLE
Image was torn 

### ISSUE THREAD

**Issue by cokecoffe** [jomjol/water-meter-system-complete#1]
<img width="899" alt="q" src="https://user-images.githubusercontent.com/1639304/65488295-6712cc00-dedb-11e9-8806-bed95e67273d.png">

<img width="559" alt="test" src="https://user-images.githubusercontent.com/1639304/65488246-3af74b00-dedb-11e9-8eaf-c96ad02b3d03.png">

**Comment by jomjol** [comment]
On what system did you use the image? Docker file with "latest" or "rolling"?
The config files included there are updated to the new configuration with the ESP32-CAM. I forgott to update the file here.
Will do this as soon as I have time to check for an updated version.

**Comment by jomjol** [comment]
Checked the problem: reference.jpg was never intended to directly use with system as the config.ini originally was assuming a 180 degree rotated image.

Set inital rotation to 0° in Config.ini and added an updated reference_masked.jpg

**Comment by cokecoffe** [comment]
> On what system did you use the image? Docker file with "latest" or "rolling"?
> The config files included there are updated to the new configuration with the ESP32-CAM. I forgott to update the file here.
> Will do this as soon as I have time to check for an updated version.

I setup the system :
pip install requirements.txt pip
 python wasserzaehler.py
,then i open the safari and input the url:   http://192.168.1.253:3000/wasserzaehler.html?url=https://raw.githubusercontent.com/cokecoffe/configuration-files/master/test1.jpg&full

image is from github here:
https://raw.githubusercontent.com/cokecoffe/configuration-files/master/test1.jpg
 
the result is show on my first image.
