### ISSUE TITLE
Rechnerisches Vermeiden von Ausgaben mit N in Ziffer 5

### ISSUE THREAD

**Issue by friedpa** [jomjol/water-meter-system-complete#13]
es kommt ja doch relativ oft vor, dass die Ziffer 5 wechselt. Bei meiner Wasseruhr startet der Wechsel circa 50 Liter vorher (also z.B. bei 422,9500 und die Erkennung funktioniert wieder circa 10 Liter nach dem Wechsel (also bei z.B. 423,0100). Dazwischen kommt das N bei der Auswertung der Ziffer 5 (z.B. 42N,9990). Könnte man nicht in diesem Bereich, also von xxxxx,09500 bis xxxxx,0100 dieses N automatisch mit dem "richtigen" Wert ersetzen? Also 422,9999 und dann weiter mit 423.0000 ....
Den Bereich könnte man dann vielleicht in der config.ini einstellbar machen (Liter vorher / Liter nachher) da wahrscheinlich jede Wasseruhr anders ist.

**Comment by jomjol** [comment]
Das wird automatisch gemacht, wenn man den Wasserzählte mit dem Parameter "&usePrevalue" aufruft. Voraussetzung ist, dass dann mindestens einmal ein vollständiger Wert (ohne "N") gelesen wurde, damit er weis wo er steht oder per "setPreValue.html?value=406.1187" ein Wert gesetzt wird.
Aktuell wird der preValue bei Neustart gelöscht. Verion mit dem Speichern in einer Datei ist in Arbeit.
