### ISSUE TITLE
Add JSON output

### ISSUE THREAD

**Issue by rkotulan** [jomjol/water-meter-system-complete#19]
Add JSON endpoint, for easy integration to 3rd party system like the home assistant.

**Comment by jomjol** [comment]
JSON Output integrated in Version 5.4.0
Make a donwload and test it.

**Comment by rkotulan** [comment]
Thank you.
Is the usage http://server:port/wasserzaeher.json?url=http://10.0.0.141:8080/photoaf.jpg ?
I downloaded a rolling wasserzaehler image. Is it right?

**Comment by rkotulan** [comment]
Here is a small typo 
![image](https://user-images.githubusercontent.com/18562096/73141958-ccddb300-4089-11ea-89ae-b3c5b1034d19.png)

**Comment by rkotulan** [comment]
Now it worked! Thank you.

**Comment by rkotulan** [comment]
One small thing.
![image](https://user-images.githubusercontent.com/18562096/73142213-79209900-408c-11ea-830a-043a5cf1d027.png)
Should not the DigitalDigicts property contain leading zeros?

**Comment by jomjol** [comment]
Thanks for the hints. The spelling was only in the README.md. The correct URL is:
`.../wasserzaehler.json...`
I removed the leadeing zero by purpuse, to have a better processing. Do you thing I should leave them in?

**Comment by rkotulan** [comment]
I think I leave them in. We have value in the Value field. And DigitalDigits is close in meaning to leave them in. What do you think?

**Comment by jomjol** [comment]
I agree on your argument and updated the code. Docker is in building. Thanks for contributing.
I will close this comment.
