### ISSUE TITLE
Error in wasseruhr.py:  No module named http.server

### ISSUE THREAD

**Issue by CyDFect** [jomjol/water-meter-system-complete#47]
When starting the container I get the following error:

Traceback (most recent call last):
  File "./wasseruhr.py", line 1, in <module>
    from http.server import HTTPServer, BaseHTTPRequestHandler
ImportError: No module named http.server

The problem seems to be, that in the Dockerfile the wasseruhr.py is called with python. Python 2.7 doesn't have the HTTPServer.
Following change in the Dockerfile seems to fix the problem:
CMD ["python3", "./wasseruhr.py"]

**Comment by jomjol** [comment]
Which image did you use? rolling oder raspi-rolling?

I have teste both (rolling on Synology NAS) and raspi-rolling (on Raspi B3) and could not get the error on a first test. But what you wrote seems logical. So I will test it, as soon as I have the access to my Raspi.

**Comment by CyDFect** [comment]
I'm using the raspi-latest.

**Comment by jomjol** [comment]
Can you please test the raspi-rolling? This should work and I'm about to make it to the raspi-latest.

**Comment by jomjol** [comment]
Problem solved
