### ISSUE TITLE
Source from USB cam

### ISSUE THREAD

**Issue by ramiws** [jomjol/water-meter-system-complete#56]
Hi, pretty cool project! I have an endoscope camera that I can plug to the RaspberryPi via USB. Is there a way for the server to use it directly ?

I was thinking to have a webpage that is using the camera then give that URL to the server. Would that work? or is there an easier way?

**Comment by jomjol** [comment]
To make this as an http image server is the easiest way - and yet recommendet.
I have an internal version, that can directly access the Raspberry Picamera (v1.3), but this is still experimental. In the same way you can extend the source code for your endoscope camera.
