### ISSUE TITLE
Readout not updating

### ISSUE THREAD

**Issue by Wauxadd** [jomjol/water-meter-system-complete#58]
I noticed that sometimes readout on top of the website is not updating even when picture has changed and also readout next to the digits and analog meters have changed correctly. Only restarting server has resolved this issue and readout is corrected after restart. Running on rasbian with docker on raspberrypi 3b

**Comment by jomjol** [comment]
Can you send me an example screen shot, next time this happens?

**Comment by Wauxadd** [comment]
Sure. im testing now raspi-rolling build. for now it has been more stable than raspi-latest. Im using Home assistant and NodeRed to make requests for readout. Dont have picture for that specific problem but here is picture wich tries to describe this problem little better.
![2020-05-24 (2)](https://user-images.githubusercontent.com/15816831/82763631-d1d12a00-9e11-11ea-9a5a-e08d40783857.png)

**Comment by jomjol** [comment]
Any updates on the tests?
If everything is okay, I will close this issue in the next days.
