### ISSUE TITLE
HomeAssistant addon!

### ISSUE THREAD

**Issue by Wauxadd** [jomjol/water-meter-system-complete#59]
It would be great to have this as a addon for Home Assistant. I have no knowledge much for coding side and that but im sure willing to test and give feedback if you ever decide to bring this for all those users on Home Assistant project. More info here: https://developers.home-assistant.io/docs/add-ons/tutorial/

**Comment by jomjol** [comment]
At the moment there is no addon planned. It is recommended to use a parser from the html output.
