### ISSUE TITLE
Possibility to dim LED

### ISSUE THREAD

**Issue by plix1014** [jomjol/water-meter-system-complete#65]
the flash LED is quite bright. I used some tissue, to dim the light, but the light is still too bright.
Would be great, if there would be some possibility to dim the white LED.
![IMG_4175](https://user-images.githubusercontent.com/45921388/119255994-c3515600-bbbe-11eb-83ea-0daf37f2bcb5.jpg)

**Comment by jomjol** [comment]
Hi, this will not work as the camera is working in auto illumination mode. So it will increase the illumination time.
